// Array (consentono la memorizzazione ordinata di una lista di elementi).

let fruits = ["ananas", "mela", "fragola"];

alert( fruits[0] ); // ananas
alert( fruits[1] ); // mela
alert( fruits[2] ); // fragola

//volendo possiamo rimpiazzare un elemento, ad esempio:

fruits[2] = 'cocomero'; // ["ananas", "mela", "cocomero"]


//si può anche aggiungere un nuovo elemento:

fruits[3] = 'albicocca'; //["ananas", "mela", "cocomero", "albicocca"]

//possiamo contare il numero degli elementi dell'array usando length

let fruits = ["ananas", "mela", "fragola"];
alert ( fruits.length ); //3

//per mostrare l'intero array si usa alert:

let fruits = ["ananas", "mela", "fragola"];
alert ( fruits ); //ananas,mela,fragola

